<a href="https://colab.research.google.com/github/DianPandus/PapbPrak/blob/master/Tugas8_Backpropagation_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bab 8 Backpropagation (1)

## Praktikum

### a) Fungsi *Binary Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:

In [21]:
def bin_enc(lbl):
    mi = min(lbl)
    length = len(bin(max(lbl) - mi + 1)[2:])
    enc = []
    for i in lbl:
      b = bin(i - mi)[2:].zfill(length)


      enc.append([int(n) for n in b])
    return enc

def bin_dec(enc, mi=0):
    lbl = []
    for e in enc:
      rounded = [int(round(x)) for x in e]
      string = ''.join(str(x) for x in rounded)
      num = int(string, 2) + mi
      lbl.append(num)
    return lbl

### b) Percobaan *Binary Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:

In [22]:
labels = 1, 2, 3, 4
enc = bin_enc(labels)
dec = bin_dec(enc, min(labels))
print(enc)
print(dec)

[[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1]]
[1, 2, 3, 4]


### c) Fungsi *One-hot Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:


In [23]:
import numpy as np
def onehot_enc(lbl, min_val=0):
  mi = min(lbl)
  enc = np.full((len(lbl), max(lbl) - mi + 1), min_val, np.int8)
  for i, x in enumerate(lbl):
    enc[i, x - mi] = 1
  return enc

def onehot_dec(enc, mi=0):
  return [np.argmax(e) + mi for e in enc]

### d) Percobaan *Binary Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:

In [24]:
labels = 1, 2, 3, 4
enc = onehot_enc(labels)
dec = onehot_dec(enc, min(labels))
print(enc)
print(dec)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[1, 2, 3, 4]


### e) Fungsi Aktivasi Sigmoid dan Derivatifnya

Tulis kode ke dalam *cell* di bawah ini:

In [25]:
def sig(X):
  return [1 / (1 + np.exp(-x)) for x in X]
def sigd(X):
  output = []
  for i, x in enumerate(X):
    s = sig([x])[0]
    output.append(s * (1 - s))
  return output

# SOAL

In [26]:
from google.colab import files
uploaded = files.upload()

# Mengimpor file CSV setelah diunggah
import pandas as pd
df = pd.read_csv('iris_csv.csv')  # Ganti 'nama_file.csv' dengan nama file yang diunggah
df.head()  # Menampilkan beberapa baris pertama data


Saving iris.csv to iris (1).csv


sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [27]:
def bin_enc_str(string_list):
    """
    Fungsi ini menerima sebuah daftar (list) dari string dan mengonversi setiap string menjadi representasi biner.
    Outputnya adalah list, di mana setiap string direpresentasikan sebagai daftar karakter biner.
    """
    binary_encoded = [[format(ord(char), '08b') for char in s] for s in string_list]
    return binary_encoded

In [28]:
def bin_dec_str(binary_list):
    """
    Fungsi ini menerima list yang sudah diencode dalam bentuk biner (dalam format list of lists),
    dan mengubahnya kembali menjadi daftar string asli.
    """
    decoded = [''.join([chr(int(b, 2)) for b in binary_string]) for binary_string in binary_list]
    return decoded

In [29]:
def onehot_enc_str(string_list):
    """
    Fungsi ini menerima sebuah daftar string unik dan mengonversi setiap string menjadi vektor one-hot encoding.
    """
    unique_classes = sorted(set(string_list))
    onehot_encoded = [[1 if s == cls else 0 for cls in unique_classes] for s in string_list]
    return onehot_encoded, unique_classes

In [30]:
def onehot_dec_str(onehot_encoded, unique_classes):
    """
    Fungsi ini menerima daftar yang sudah diencode dalam bentuk one-hot dan daftar kelas unik,
    dan mengubahnya kembali menjadi daftar string asli.
    """
    decoded = [unique_classes[vec.index(1)] for vec in onehot_encoded]
    return decoded

In [31]:
# Mendefinisikan 'kelas' dengan mengekstrak kolom 'class' dari DataFrame
kelas = df['class'].tolist()
binary_encoded_kelas = bin_enc_str(kelas)
decoded_binary_kelas = bin_dec_str(binary_encoded_kelas)

onehot_encoded_kelas, unique_classes = onehot_enc_str(kelas)
decoded_onehot_kelas = onehot_dec_str(onehot_encoded_kelas, unique_classes)

# Menampilkan hasil pengujian untuk verifikasi
print("Binary Encoded Kelas:", binary_encoded_kelas[:2])
print("Decoded Binary Kelas:", decoded_binary_kelas[:2])
print("One-Hot Encoded Kelas:", onehot_encoded_kelas[:2])
print("Decoded One-Hot Kelas:", decoded_onehot_kelas[:2])

Binary Encoded Kelas: [['01001001', '01110010', '01101001', '01110011', '00101101', '01110011', '01100101', '01110100', '01101111', '01110011', '01100001'], ['01001001', '01110010', '01101001', '01110011', '00101101', '01110011', '01100101', '01110100', '01101111', '01110011', '01100001']]
Decoded Binary Kelas: ['Iris-setosa', 'Iris-setosa']
One-Hot Encoded Kelas: [[1, 0, 0], [1, 0, 0]]
Decoded One-Hot Kelas: ['Iris-setosa', 'Iris-setosa']
